import mongoose from "mongoose";

const storeAlertsSchema = new mongoose.Schema(
  {
    storeId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Store",
      required: true,
      unique: true,
    },
    isEmailEnabled: { type: Boolean, default: false },
    provider: { type: String, enum: ["gmail", "custom"], default: "gmail" },
    smtpHost: { type: String, default: "smtp.gmail.com" },
    smtpPort: { type: Number, default: 587 },
    emailAddress: { type: String, trim: true },
    appPassword: { type: String }, // Store App Passwords generated by Gmail/Yahoo/etc.
  },
  { timestamps: true }
);

export default mongoose.models.StoreAlerts || mongoose.model("StoreAlerts", storeAlertsSchema);