import mongoose from "mongoose";

const alertTemplateSchema = new mongoose.Schema({
  eventType: {
    type: String,
    enum: ["order_placed", "order_shipped", "order_delivered", "order_canceled", "order_returned", "custom"],
    required: true,
  },
  name: { type: String, required: true },
  subject: { type: String, required: true },
  body: { type: String, required: true },
  isActive: { type: Boolean, default: true },
});

const storeAlertsSchema = new mongoose.Schema(
  {
    storeId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Store",
      required: true,
      unique: true,
    },
    isEmailEnabled: { type: Boolean, default: false },
    provider: { type: String, enum: ["gmail", "custom"], default: "gmail" },
    smtpHost: { type: String, default: "smtp.gmail.com" },
    smtpPort: { type: Number, default: 587 },
    emailAddress: { type: String, trim: true },
    appPassword: { type: String }, // Store App Passwords generated by Gmail/Yahoo/etc.
    templates: [alertTemplateSchema],
  },
  { timestamps: true }
);

export default mongoose.models.StoreAlerts || mongoose.model("StoreAlerts", storeAlertsSchema);